<a href="https://colab.research.google.com/github/ridhikapila27/Deep_learning/blob/main/Lab7_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
### import libraries
import torch
import torch.nn as nn
import numpy as np


In [36]:
# set layer parameters
input_size = 9 # number of features to extract (e.g., number of data channels)
hidden_size = 16 # number of units in the hidden state
num_layers = 1 # number of vertical stacks of hidden layers (note: only the final layer gives an output)
actfun = 'tanh'
bias = True
# create an RNN instance
rnn = nn.RNN(input_size,hidden_size,num_layers,nonlinearity=actfun,bias=bias)
print(rnn)
# check out the source code for more detailed info about this class
??nn.RNN
# set data parameters
seqlength = 5
batchsize = 2
# create some data
X = torch.rand(seqlength,batchsize,input_size)
# create a hidden layer (typically initialized as zeros)
hidden = torch.zeros(num_layers,batchsize,hidden_size)
# run some data through the model and show the output sizes
y,h = rnn(X,hidden)
print(f' Input shape: {list(X.shape)}')
print(f'Hidden shape: {list(h.shape)}')
print(f'Output shape: {list(y.shape)}')
## Default hidden state is all zeros if nothing specified:
y,h1 = rnn(X,hidden)
print(h1), print('\n\n')
y,h2 = rnn(X)
print(h2), print('\n\n')
# they're the same! (meaning default=zeros)
print(h1-h2)
# Check out the learned parameters and their sizes
for p in rnn.named_parameters():
  if 'weight' in p[0]:
     print(f'{p[0]} has size {list(p[1].shape)}')

RNN(9, 16)
 Input shape: [5, 2, 9]
Hidden shape: [1, 2, 16]
Output shape: [5, 2, 16]
tensor([[[ 0.2264, -0.1959, -0.8311, -0.2815,  0.0598,  0.2627, -0.5895,
           0.3471,  0.5590,  0.4906,  0.0392, -0.4393, -0.0219, -0.0845,
           0.5504,  0.3714],
         [ 0.3592,  0.0555, -0.6684, -0.5904,  0.0446, -0.0311, -0.5923,
          -0.1613,  0.5936,  0.3147,  0.0308, -0.4747, -0.3216, -0.4296,
           0.5624,  0.3183]]], grad_fn=<StackBackward0>)



tensor([[[ 0.2264, -0.1959, -0.8311, -0.2815,  0.0598,  0.2627, -0.5895,
           0.3471,  0.5590,  0.4906,  0.0392, -0.4393, -0.0219, -0.0845,
           0.5504,  0.3714],
         [ 0.3592,  0.0555, -0.6684, -0.5904,  0.0446, -0.0311, -0.5923,
          -0.1613,  0.5936,  0.3147,  0.0308, -0.4747, -0.3216, -0.4296,
           0.5624,  0.3183]]], grad_fn=<StackBackward0>)



tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],
 

In [39]:
class RNNnet(nn.Module):
  def __init__(self,input_size,num_hidden,num_layers):
    super().__init__()
    # store parameters
    self.input_size = input_size
    self.num_hidden = num_hidden
    self.num_layers = num_layers
    # RNN Layer
    self.rnn = nn.RNN(input_size,num_hidden,num_layers)
    # linear layer for output
    self.out = nn.Linear(num_hidden,1)
    def forward(self,x):
      print(f'Input: {list(x.shape)}')
      # initialize hidden state for first input
      hidden = torch.zeros(self.num_layers,batchsize,self.num_hidden)
      print(f'Hidden: {list(hidden.shape)}')
      # run through the RNN layer
      y,hidden = self.rnn(x,hidden)
      print(f'RNN-out: {list(y.shape)}')
      print(f'RNN-hidden: {list(hidden.shape)}')
      # pass the RNN output through the linear output layer
      o = self.out(y)
      print(f'Output: {list(o.shape)}')
      return o,hidden
  # create an instance of the model and inspect
    net = RNNnet(input_size,hidden_size,num_layers)
    print(net), print(' ')
    # and check out all learnable parameters
    for p in net.named_parameters():
      print(f'{p[0]} has size {list(p[1].shape)}')
      # test the model with some data
      # create some data
      X = torch.rand(seqlength,batchsize,input_size)
      y = torch.rand(seqlength,batchsize,1)
      yHat,h = net(X)
      # try a loss function
      lossfun = nn.MSELoss()
      lossfun(yHat,y)